name: ScoreboardManager
version: ${project.version}
main: dev.thelecrafter.dimensionz.scoreboardmanager.ScoreboardManagerPlugin
api-version: 1.16
commands:
  scoreboardreload:
    permission: scoreboardmanager.command.reload
    usage: /scoreboardreload
  disablescoreboard:
    permission: scoreboardmanager.command.disablescoreboard
    usage: /disablescoreboard
